# Generated by Django 5.0.6 on 2024-08-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hadisler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=300)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
