# Generated by Django 5.0.6 on 2024-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadisler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadisler',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
