# Generated by Django 5.0.6 on 2024-08-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadisler', '0002_alter_hadisler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadisler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
