# Generated by Django 5.0.6 on 2024-08-17 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadisler', '0004_hadisler_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadisler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadisler', to=settings.AUTH_USER_MODEL, verbose_name='İdareci'),
        ),
    ]
