# Generated by Django 5.0.6 on 2024-08-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='is_east',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
